feat: [ZNO-2078] add custom plugin to provide ukrainian region map for superset
raccoongang/superset pull request #6
Opened 2023-09-26 12:44 UTC by YuriiBorovenskyi

**Description:**
* add custom plugin to provide Ukrainian region map for superset
* add ability to build map of Ukraine by name of regions
* add Ukrainian translations - po, json

**YouTrack:** https://youtrack.raccoongang.com/issue/ZNO-2078

**Merge checklist:**
* [ ] All reviewers approved
* [x] Demo status: OK
* [ ] Commits are squashed

2023-09-27 07:40 UTC, NikolayBorovenskiy requested changes
One tiny fix and let's go to check it out.

2023-09-27 07:40 UTC, NikolayBorovenskiy commented on superset/viz.py
> +
Please fix this doc string.

2023-09-27 07:40 UTC, NikolayBorovenskiy commented
@YuriiBorovenskyi Pay attention to CI. It is hardly broken now.

2023-09-30 18:05 UTC, YuriiBorovenskyi commented on superset/viz.py
> +
Done.

2023-10-03 15:37 UTC, merged